ACL問題追加
ECCNetLab/problems pull request #23
Opened 2022-05-30 09:36 UTC by Minomusi64

ACL問題作ってみました。レビューお願いします。

2022-06-01 06:21 UTC, K-shir0 requested changes
@Minomusi64 
確認しました。全体的に既存のフォーマットに準拠していないのでマネしながら参考にすると良いと思います。図に関してなのですが、機器名と背景の四角に枠線は必要でしょうか？

2022-06-01 06:21 UTC, K-shir0 commented on basic_acl/README.md
> +----
あまり既存のフォーマットに準拠していないのでなるように修正して欲しいです。
ここあたりが参考になると思います。

階層を意識して分けるのがコツです

https://github.com/ECCNetLab/problems/tree/main/basic_vrrp01

2022-06-01 06:21 UTC, K-shir0 commented on README.md
> +- [ACLをしてみよう](basic_acl/README.md)
全体的にファイル名がおかしいです。

他のファイルを見てもわかりますが `basic_○○01` として下さい。

2022-06-01 09:08 UTC, Minomusi64 commented on README.md
> +- [ACLをしてみよう](basic_acl/README.md)
レビューありがとうございます！ファイル名に01を追加しました。

2022-06-03 11:01 UTC, Minomusi64 commented on basic_acl/README.md
> +----
レビューありがとうございます！問題文を修正しました。
もう1度レビューお願いします。

2022-06-05 11:47 UTC, K-shir0 requested changes
@Minomusi64 
一カ所だけコメントしました。あとコンフリクトが発生しているので解消して欲しいです。

2022-06-05 11:47 UTC, K-shir0 commented on basic_acl01/README.md
> +        1. 同上 *※Roouter1との設定の違いに気を付けて*
```suggestion
        1. 同上 *※Roouter1との設定の違いに注意*
```

2022-06-07 08:53 UTC, Minomusi64 commented on basic_acl01/README.md
> +        1. 同上 *※Roouter1との設定の違いに気を付けて*
修正ありがとうございます！コンフリクト解消しました。

2022-06-07 17:45 UTC, K-shir0 requested changes

2022-06-07 17:45 UTC, K-shir0 commented on basic_acl01/README.md
> +        1. 同上 *※Roouter1との設定の違いに気を付けて*
ここの箇所が修正されてないっぽです

2022-06-07 17:46 UTC, K-shir0 commented
@Minomusi64 
再レビューを依頼する際は画像右上のくるくるを押すことで依頼できます。
<img width="324" alt="image" src="https://user-images.githubusercontent.com/50326556/172448457-2f1f7b9b-b508-49aa-8f20-a00756ae82ea.png">

2022-06-10 10:01 UTC, K-shir0 approved these changes
@Minomusi64 LGTM!

2022-06-10 10:06 UTC, merged